name: em-stitching
home: https://github.com/hmcts/rpa-em-stitching-api
version: 1.0.27
apiVersion: v2
description: Helm chart for the HMCTS EM Stitching API
maintainers:
  - name: HMCTS EM Team
dependencies:
  - name: java
    version: 4.1.4
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
