java:
  image: 'hmctspublic.azurecr.io/em/stitching:latest'
  ingressHost: em-stitching-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 8080
  readinessTimeout: 5
  readinessFailureThreshold: 10
  livenessTimeout: 5
  livenessFailureThreshold: 10
  aadIdentityName: em
  keyVaults:
    em-stitching:
      resourceGroup: em-stitching
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: APPINSIGHTS_INSTRUMENTATIONKEY
        - name: docmosis-access-key
          alias: DOCMOSIS_ACCESS_KEY
        - name: microservicekey-em-stitching-api
          alias: S2S_KEY
        - name: stitching-POSTGRES-PASS
          alias: SPRING_DATASOURCE_PASSWORD
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  environment:
    SPRING_DATASOURCE_PORT: 5432
    SPRING_DATASOURCE_NAME: emstitch
    SPRING_DATASOURCE_OPTIONS: "?sslmode=require"
    SPRING_DATASOURCE_HOST: em-stitching-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    SPRING_DATASOURCE_USERNAME: emstitch@em-stitching-postgres-db-v11-{{ .Values.global.environment }}
    DB_CONNECTION_TIMEOUT: 5000
    RUN_DB_MIGRATION_ON_STARTUP: 'false'
    # Regardless of environment, point towards AAT instances. Overwrite in product charts etc.
    IDAM_API_BASE_URI: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    S2S_BASE_URI: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DM_STORE_APP_URL: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCMOSIS_ENDPOINT: https://docmosis.{{ .Values.global.environment }}.platform.hmcts.net/rs/convert
    DOCMOSIS_RENDER_ENDPOINT: https://docmosis.{{ .Values.global.environment }}.platform.hmcts.net/rs/render
    CDAM_URL: http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    ENABLE_DB_MIGRATE: false
    REFORM_SERVICE_NAME: rpa-em-stitching-api
    REFORM_TEAM: rpa-em-stitching-api
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    PACKAGES_NAME: em-stitch
    PACKAGES_PROJECT: evidence
    PACKAGES_ENVIRONMENT: preview
    JSON_CONSOLE_PRETTY_PRINT: false
    SHOW_SQL: false
    ENDPOINTS_HEALTH_SENSITIVE: false
    ENDPOINTS_INFO_SENSITIVE: false
    CASE_WORKER_ROLES: caseworker-probate,caseworker-cmc,caseworker-sscs,caseworker-divorce
    ENABLE_IDAM_HEALTH_CHECK: false
    ENABLE_S2S_HEALTH_CHECK: false
    SERVER_PORT: 8080
    TASK_ENV: documentTaskLock-{{ .Values.global.environment }}
    CALLBACK_MAX_ATTEMPTS: 3
    DOCUMENT_TASK_MILLISECONDS: 2000
    HISTORIC_DOCUMENT_TASKS_NO_OF_RETENTION_DAYS: 180
    HISTORIC_DOCUMENT_TASKS_NO_OF_RECORDS: 5000
    HISTORIC_DOCUMENT_TASKS_CRONJOB_SCHEDULE: 0 15 22 * * ?
    HISTORIC_EXECUTIONS_RETENTION_ENABLED: true
    HTTP_CLIENT_CONNECT_TIMEOUT: 30000
    HTTP_CLIENT_SOCKET_TIMEOUT: 60000
    APPLICATIONINSIGHTS_INSTRUMENTATION_LOGGING_LEVEL: INFO

ccd:
  enabled: false
xui-webapp:
  enabled: false
idam-pr:
  enabled: false
ia-case-api:
  enabled: false
ia-case-payments-api:
  enabled: false
ia-case-documents-api:
  enabled: false
ia-case-notifications-api:
  enabled: false
ia-home-office-integration-api:
  enabled: false
ia-aip-frontend:
  enabled: false
ccd-case-document-am-api:
  enabled: false
em-ccdorc:
  enabled: false
