stitching:
  postgresql:
    postgresqlUsername: emstitch
    postgresqlPassword: emstitch
    nameOverride: em-stitching-db
  image: 'hmctspublic.azurecr.io/em/stitching:latest'
  applicationPort: 8080
  readinessDelay: 30
  readinessTimeout: 5
  readinessPeriod: 15
  readinessFailureThreshold: 10
  livenessDelay: 30
  livenessTimeout: 5
  livenessPeriod: 15
  livenessFailureThreshold: 10
  aadIdentityName: em
  keyVaults:
    em-stitching:
      resourceGroup: em-stitching
      secrets:
        - AppInsightsInstrumentationKey
        - docmosis-access-key
        - microservicekey-em-stitching-api
        - stitching-POSTGRES-DATABASE
        - stitching-POSTGRES-HOST
        - stitching-POSTGRES-PASS
        - stitching-POSTGRES-PORT
        - stitching-POSTGRES-USER
  environment:
    SPRING_DATASOURCE_URL: jdbc:postgresql://em-stitching-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com:5432/javadatabase?ssl=disable
    SPRING_DATASOURCE_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    RUN_DB_MIGRATION_ON_STARTUP: 'false'
    # Regardless of environment, point towards AAT instances. Overwrite in product charts etc.
    IDAM_API_BASE_URI: https://idam-api.aat.platform.hmcts.net
    S2S_BASE_URI: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    IDAM_WEBSHOW_WHITELIST: https://em-show-aat.service.core-compute-aat.internal/oauth2/callback
    DM_STORE_APP_URL: http://dm-store-aat.service.core-compute-aat.internal

    ENABLE_DB_MIGRATE: true
    REFORM_SERVICE_NAME: rpa-em-stitching-api
    REFORM_TEAM: rpa-em-stitching-api
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    PACKAGES_NAME: em-stitch
    PACKAGES_PROJECT: evidence
    PACKAGES_ENVIRONMENT: preview
    JSON_CONSOLE_PRETTY_PRINT: false
    LOG_OUTPUT: single
    ROOT_LOGGING_LEVEL: INFO
    LOG_LEVEL_SPRING_WEB: INFO
    LOG_LEVEL_DM: INFO
    SHOW_SQL: true
    ENDPOINTS_HEALTH_SENSITIVE: false
    ENDPOINTS_INFO_SENSITIVE: false
    CASE_WORKER_ROLES: caseworker-probate,caseworker-cmc,caseworker-sscs,caseworker-divorce
    ENABLE_IDAM_HEALTH_CHECK: false
    ENABLE_S2S_HEALTH_CHECK: false
    ENABLE_LIQUIBASE: false
    SERVER_PORT: 8080
    TASK_ENV: documentTaskLock-aat
